version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.Api/Dockerfile
    ports:
      - "7106:7106"
    environment:
      - ASPNETCORE_URLS=http://*:7106
    depends_on: [mssql, seq_logs]
    networks:
      - app-network
  conferenceattendees.mvc:
    image: ${DOCKER_REGISTRY-}conferenceattendeesmvc
    build:
      context: .
      dockerfile: ConferenceAttendees.MVC/Dockerfile
    ports:
      - "7230:7230"
    environment:
      - ASPNETCORE_URLS=http://*:7230
    depends_on:
      - conferenceattendees.api
    networks:
      - app-network
  mssql:
    image: "trevoirwilliams/conferenceattendeedb"
    container_name: sql2
    hostname: mssql
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1401:1433" 
    networks:
      - app-network
  seq_logs:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
    networks:
      - app-network
  nginx:
    build:
      context: . 
      dockerfile: nginx/Dockerfile
    ports:
      - "44391:44391"
    depends_on:
      - conferenceattendees.mvc
    networks:
      app-network:
        aliases:
          - "conferenceattendees.com"
          - "api.conferenceattendees.com"
    restart: always

networks:
  app-network:
    driver: bridge