version: '3.4'

services:
  conferenceattendees.api:
    image: ${DOCKER_REGISTRY-}conferenceattendeesapi
    build:
      context: .
      dockerfile: ConferenceAttendees.Api/Dockerfile
    ports:
      - "7106:8081"
    depends_on: [mssql, seq]
  conferenceattendees.ui:
    image: conferenceattendees.ui
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - "8083:80"
    depends_on: [conferenceattendees.api]
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql2
    hostname: mssql
    environment:
      - SA_PASSWORD=P@ssword1
      - ACCEPT_EULA=Y
    restart: unless-stopped
    ports:
      - "1400:1433"
  seq:
    image: datalust/seq
    restart: unless-stopped
    ports:
      - "5342:80"
    environment:
      - ACCEPT_EULA=Y
